### ISSUE TITLE
facebook share doesn't really work

### ISSUE THREAD

**Issue by kapouer** [popomore/social-share#4]
Did you tried to share to facebook recently ? I have troubles doing so.

**Comment by kapouer** [comment]
it seems sharer.php has been deprecated by facebook. The equivalent would be feed dialog.

**Comment by kapouer** [comment]
ohhhhh it only works if the link being shared points to a page with opengraph tags or meta. (like og:url, og:title, etc...).

**Comment by popomore** [comment]
Thanks, I will check it.

**Comment by popomore** [comment]
More detail  http://stackoverflow.com/questions/12547088/how-do-i-customize-facebooks-sharer-php

Maybe I should switch to like button.

https://developers.facebook.com/docs/reference/plugins/like/
